clone_depth: 5

environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x64
  - npm install -g npm vsce
  - del package-lock.json /f
  - npm install >> log.txt

build_script:
  - npm run compile

artifacts:
  - path: '**\*.vsix'
    name: quickTask.vsix

test_script:
  - node --version
  - npm run test

deploy:
  release: quickTask-v$(appveyor_build_version)
  description: 'quickTask vsix package'
  provider: GitHub
  artifact: /.*\.vsix/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
